### ISSUE TITLE
AJAX Loading in YAG Plugin fails

### ISSUE THREAD

**Issue by wowawebdesign** [YAG-Gallery/yag#48]
Trying to select a gallery in the yag plugin doesn't work because of a missing ajax.php in the typo3-directory. (TYPO3 7.5)
![yag-ajax](https://cloud.githubusercontent.com/assets/343511/10536845/64170eb4-73ee-11e5-88b6-733383e07139.png)

**Comment by daniellienert** [comment]
Hey Wolfgang, for apache users there has been a .htaccess that add a legacy fallback of the ajax.php - that why I haven't found that problem. 

Should be fixed with: https://github.com/YAG-Gallery/yag/commit/58c98403c7422dc2e7569629d48425c64660c57b

Please check if that fixes your problem.

Cheers, 
Daniel

**Comment by wowawebdesign** [comment]
Hi Daniel, yes, now it works! :)
