### ISSUE TITLE
Roadmap for TYPO3 V8

### ISSUE THREAD

**Issue by akerssies** [YAG-Gallery/yag#99]
First of all, great gallery plugin. It's working great on v7 LTS and v6 LTS.

Will this plugin be updated to work on TYPO3 v8 LTS ? 
If so, is there a roadmap on when to expect support for v8 ?

**Comment by daniellienert** [comment]
Hey @akerssies, 
Thanks a lot for the kind words. Currently there is no roadmap for upgrading YAG for 8.0. As my free-time open source work is currently dedicated to Neos. Sure, I will help upgrading the gallery as soon as an customer TYPO3 8.0 project needs it. 
But luckily it is open source!  So I would be glad to integrate pull requests that update YAG for 8.0.

Cheers, 
Daniel

**Comment by delgranja** [comment]
Hey Daniel
I like your Yag Gallery. That's why I've used it on several websites. Now my hoster will provide the PHP version for the Typo3 7 ap until the end of the year. I do not want to go bust, but is there a possibility that the Yag Gallery will be updated for Typo3 version 8 by the end of August? If not, I find myself forced to set up another gallery, which would be very unpleasant. Thank you for your answer.
Greetings Anja

**Comment by mmasmoudi** [comment]
I really like this Gallery, i find it fancy, i wish that it will be upgraded to the Typo3 v.9.

Thanks a lot Daniel and all developers.
